# Generated by Django 5.1.7 on 2025-03-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(default=2020),
        ),
    ]
